@startuml

left to right direction

actor "Membro/Aluno" as Membro
actor "Instrutor" as Instrutor
actor "Gerente" as Gerente

rectangle "Sistema da Academia" {

    usecase "Realizar Check-in" as UC1
    usecase "Visualizar Ficha\nde Treino" as UC2
    usecase "Consultar Aulas\nDisponíveis" as UC3
    usecase "Inscrever-se em Aula" as UC4
    usecase "Cancelar Inscrição" as UC5
    usecase "Registrar Frequência" as UC6

    usecase "Consultar Alunos" as UC7
    usecase "Criar Ficha de Treino" as UC8
    usecase "Atualizar Ficha de Treino" as UC9

    usecase "Consultar Frequência" as UC10
    usecase "Gerar Relatório\nde Frequência" as UC11
}

Membro --> UC1
Membro --> UC2
Membro --> UC3
Membro --> UC4
Membro --> UC5

UC1 ..> UC6 : <<include>>
UC4 ..> UC3 : <<include>>

Instrutor --> UC7
Instrutor --> UC2
Instrutor --> UC8
Instrutor --> UC9

Gerente --> UC10
Gerente --> UC11

UC11 ..> UC10 : <<include>>

@enduml