@startuml

left to right direction

actor Cliente
actor "Funcionário da Entrada" as Funcionario
actor "Operadora de Cartão" as Cartao

rectangle "Sistema de Cinema" {

    usecase "Consultar filmes\nem cartaz" as UC1
    usecase "Consultar horários\ndas sessões" as UC2
    usecase "Comprar ingresso" as UC3
    usecase "Selecionar sessão" as UC4
    usecase "Realizar pagamento" as UC5
    usecase "Gerar ingresso\ncom QR Code" as UC6

    usecase "Validar ingresso" as UC7
    usecase "Ler QR Code" as UC8
    usecase "Verificar validade" as UC9
}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC3

UC3 ..> UC4 : <<include>>
UC3 ..> UC5 : <<include>>
UC3 ..> UC6 : <<include>>

Cartao --> UC5

Funcionario --> UC7

UC7 ..> UC8 : <<include>>
UC7 ..> UC9 : <<include>>

@enduml