@startuml
left to right direction

actor "Usuário" as Usuario
actor "Serviço de Inteligência Artificial" as IA

rectangle "IA para Rotinas" {

    usecase "Gerar rotina personalizada" as Gerar
    usecase "Alterar rotina" as Alterar
    usecase "Gerar rotina novamente" as Regerar
}

Usuario --> Gerar
Usuario --> Alterar
Usuario --> Regerar

Gerar --> IA
Regerar --> IA

@enduml